name: Node CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Yarn
        run: npm install -g yarn
      - name: Start Build flows
        working-directory: .
        run: |
          npm install
          npm run build
#          yarn install
#          yarn build