name: Node CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]

    steps:
      - uses: actions/checkout@v3.0.0

      - name: Setup Node.js Version ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2.1.7
        with:
          path: node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Setup yarn
        run: npm i -g yarn

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::596122180862:user/S3Access
          aws-region: ap-northeast-2

      - name: Copy files to the test website with the AWS CLI
        run: aws s3 sync . s3://github-actions-react

#      - name: Deploy to Amazon S3
#        run: |
#          aws s3 cp \
#            --recursive \
#            --region ap-northeast-2 \
#            build s3://github-actions-react